// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdU14oBoxmOWtHEidQZz8WNby1C32cSrE',
    appId: '1:338850178702:web:768af8f0618308d2c5cbdf',
    messagingSenderId: '338850178702',
    projectId: 'flutterrxvote',
    authDomain: 'flutterrxvote.firebaseapp.com',
    storageBucket: 'flutterrxvote.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxmEJ635bI7b2EwI0hOcUJnailRUNICW4',
    appId: '1:338850178702:android:7cd1f24536c3682fc5cbdf',
    messagingSenderId: '338850178702',
    projectId: 'flutterrxvote',
    storageBucket: 'flutterrxvote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN-lsRiq55FqxeKS7sFiDeN3FPkl9vYu8',
    appId: '1:338850178702:ios:f15eaf1227a0829cc5cbdf',
    messagingSenderId: '338850178702',
    projectId: 'flutterrxvote',
    storageBucket: 'flutterrxvote.appspot.com',
    iosClientId: '338850178702-7jbiltfs5ulmjpntuvk1i7v3g80ah2vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRxVote',
  );
}
